Compatible change for cekit-3.6.0
from the generated Dockerfile
  - env does not work for modules.
  - artifact has to have the right target name.
added Pipfile

diff --git a/modules/spark/install b/modules/spark/install
--- a/modules/spark/install
+++ b/modules/spark/install
@@ -11,8 +11,8 @@ fullname=$(find $ARTIFACTS_DIR -name spark-[0-9.]*\.tgz)
 
 # Make a place for spark to go (dupe what's done in common in case we're standalone)
 if ! [ -d $SPARK_INSTALL ]; then
-    mkdir -p $SPARK_INSTALL/conf
-    ln -sfn $SPARK_INSTALL/distro $SPARK_HOME
+  mkdir -p $SPARK_INSTALL/conf
+  ln -sfn $SPARK_INSTALL/distro $SPARK_HOME
 fi
 
 pushd $SPARK_INSTALL
@@ -22,15 +22,22 @@ ln -s $(basename $fullname .tgz) distro
 rm $(basename $fullname)
 popd
 
+# XXX: hack for issue https://issues.apache.org/jira/browse/SPARK-28921
+# https://stackoverflow.com/questions/57643079/kubernetes-watchconnectionmanager-exec-failure-http-403
+rm -f $SPARK_HOME/jars/kubernetes-client-*.jar
+rm -f $SPARK_HOME/jars/kubernetes-model-*.jar
+cp $ARTIFACTS_DIR/kubernetes-*.jar $SPARK_HOME/jars
+chmod a+r $SPARK_HOME/jars/kubernetes-*.jar
+
 # Add in the configuration files (from the common module)
 pushd $SPARK_INSTALL/conf
 for conf_file in *; do
-    if ! [ -f "$SPARK_HOME"/conf/$conf_file ]; then
-	echo Moving $conf_file to $SPARK_HOME/conf
-        mv $conf_file $SPARK_HOME/conf
-    else
-	echo Not moving $conf_file, $SPARK_HOME/conf/$conf_file already exists
-    fi
+  if [ ! -f "$SPARK_HOME"/conf/$conf_file ]; then
+    echo Moving $conf_file to $SPARK_HOME/conf
+    mv $conf_file $SPARK_HOME/conf
+  else
+    echo Not moving $conf_file, $SPARK_HOME/conf/$conf_file already exists
+  fi
 done
 popd
 
@@ -40,13 +47,13 @@ chown 185:0 $SPARK_INSTALL/distro && chmod g+rwX $SPARK_INSTALL/distro
 # Search for the spark entrypoint file and copy it to $SPARK_INSTALL
 entry=$(find $SPARK_HOME/kubernetes -name entrypoint.sh)
 if [ -n "$entry" ]; then
-    cp $entry $SPARK_INSTALL
+  cp $entry $SPARK_INSTALL
 
-    # We have to patch the entrypoint to toggle error checking
-    # around the uidentry check for 2.3 (fix on the way)
-    sed -i '/^uidentry/i set +e' $SPARK_INSTALL/entrypoint.sh
-    sed -i '/^uidentry/a set -e' $SPARK_INSTALL/entrypoint.sh
+  # We have to patch the entrypoint to toggle error checking
+  # around the uidentry check for 2.3 (fix on the way)
+  sed -i '/^uidentry/i set +e' $SPARK_INSTALL/entrypoint.sh
+  sed -i '/^uidentry/a set -e' $SPARK_INSTALL/entrypoint.sh
 
-    # We also want to get rid of the tini invocation
-    sed -i "s@exec /sbin/tini -s --@exec@" $SPARK_INSTALL/entrypoint.sh
+  # We also want to get rid of the tini invocation
+  sed -i "s@exec /sbin/tini -s --@exec@" $SPARK_INSTALL/entrypoint.sh
 fi
